// This file is part of Fuxedo
// Copyright (C) 2017 Aivars Kalvans <aivars.kalvans@gmail.com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

#include <clara.hpp>
#include <iostream>
#include <string>
#include <vector>

#include <unistd.h>
#include <cstdio>

#include "misc.h"

// The code generated looks crazy at first
// but it matches the one generated by Tuxedo as close as needed to build
// tuxmodule (Python wrapper) and some other code.
static void gencode(
    FILE *fout,
    const std::vector<std::pair<std::string, std::string>> &services,
    bool threads) {
  fprintf(fout,
          R"(#include <atmi.h>
#include <stdio.h>
#include <xa.h>

#if defined(__cplusplus)
extern "C" {
#endif
)");

  for (const auto &serviceinfo : services) {
    fprintf(fout, "void %s(TPSVCINFO *);\n", serviceinfo.first.c_str());
  }

  fprintf(fout,
          R"(int _tmrunserver(int);
extern struct xa_switch_t tmnull_switch;
extern int _tmbuilt_with_thread_option;
#if defined(__cplusplus)
}
#endif

static struct tmdsptchtbl_t _tmdsptchtbl[] = {
)");

  for (const auto &serviceinfo : services) {
    fprintf(fout, "  {\"%s\", \"%s\", %s, 0, 0},\n", serviceinfo.first.c_str(),
            serviceinfo.second.c_str(), serviceinfo.second.c_str());
  }
  fprintf(fout, "  {NULL, NULL, NULL, 0, 0}\n};\n");

  fprintf(fout,
          R"(static struct tmsvrargs_t tmsvrargs = {
                                       &tmnull_switch, _tmdsptchtbl,
                                       0,
                                       tpsvrinit, tpsvrdone,
                                       _tmrunserver,
                                       NULL, NULL, NULL, NULL,
                                       tprminit,
                                       tpsvrthrinit, tpsvrthrdone };

struct tmsvrargs_t *_tmgetsvrargs() {
  return &tmsvrargs;
}

int main(int argc, char **argv) {
)");

  fprintf(fout, "  _tmbuilt_with_thread_option = %d;\n", threads ? 1 : 0);
  fprintf(fout, "  return _tmstartserver(argc, argv, _tmgetsvrargs());\n");
  fprintf(fout, "}\n");
}

static auto parse_services(const std::vector<std::string> &services) {
  std::vector<std::pair<std::string, std::string>> result;
  for (const auto &service : services) {
    result.push_back(std::make_pair(service, service));
  }
  return result;
}

int main(int argc, char *argv[]) {
  bool show_help = false;
  bool verbose = false;
  bool keep = false;
  bool threads = false;

  std::string outfile;
  std::string rmname;

  std::vector<std::string> services;
  std::vector<std::string> firstfiles;
  std::vector<std::string> lastfiles;

  auto parser =
      clara::Help(show_help) |
      clara::Opt(verbose)["-v"]("write compilation command to stdout") |
      clara::Opt(keep)["-k"]("keep generated C code") |
      clara::Opt(threads)["-t"]("build multi-threaded server") |
      clara::Opt(firstfiles, "firstfiles")["-f"](
          "compilation parameters to include before Fuxedo libraries") |
      clara::Opt(lastfiles, "lastfiles")["-l"](
          "compilation parameters to include after Fuxedo libraries") |
      clara::Opt(services, "services")["-s"]("service mapping") |
      clara::Opt(rmname, "rmname")["-r"]("resource manager name") |
      clara::Opt(outfile, "outfile")["-o"]("output file name");

  auto result = parser.parse(clara::Args(argc, argv));
  if (!result) {
    std::cerr << parser;
    return -1;
  }
  if (show_help) {
    std::cout << parser;
    return 0;
  }

  const char *tuxdir = std::getenv("TUXDIR");
  if (tuxdir == nullptr) {
    tuxdir = "";
  }

  const char *cc = std::getenv("CC");
  if (cc == nullptr) {
    cc = "cc";
  }

  const char *cflags = std::getenv("CFLAGS");

  char tmpname[] = "fuxedo-XXXXXX";
  int fd = mkstemp(tmpname);
  FILE *fout = fdopen(fd, "w");

  gencode(fout, parse_services(services), threads);

  fclose(fout);

  std::string filename = std::string(tmpname) + ".c";
  rename(tmpname, filename.c_str());

  std::vector<std::string> cmd;
  cmd.push_back(cc);
  cmd.push_back(filename);
  cmd.push_back(std::string("-I") + tuxdir + "/include");
  cmd.insert(cmd.end(), firstfiles.begin(), firstfiles.end());
  cmd.push_back(std::string("-L") + tuxdir + "/lib");
  cmd.push_back("-lfuxedo");
  cmd.push_back("-lpthread");
  cmd.push_back("-o");
  cmd.push_back(outfile);
  cmd.insert(cmd.end(), lastfiles.begin(), lastfiles.end());

  auto command = join(cmd, " ");

  if (verbose) {
    std::cout << command << std::endl;
  }

  int rc = std::system(command.c_str());
  if (!keep) {
    unlink(filename.c_str());
  }
  return rc;
}
