name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./autogen.sh && ./configure --prefix=/home/runner/fuxbin
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make installcheck
      run: make install && make installcheck
